export const STORY_TYPES = [
  { id: 'Problem → Solution', label: 'Problem → Solution', desc: 'Identifies pain point, frustration, introduces product, demonstrates relief and solution.' },
  { id: 'Unboxing', label: 'Unboxing', desc: 'Sensory package unboxing, opening reveal, first impression, product details, initial usage.' },
  { id: 'Lifestyle', label: 'Lifestyle', desc: 'Seamless integration into daily routine, aspirational vibe, emotional fulfillment.' },
  { id: 'Testimonial', label: 'Testimonial', desc: 'Authentic creator testimony, personal experience, before/after impact, recommendation.' },
  { id: 'Before → After', label: 'Before → After', desc: 'Dramatic or relatable transformation, visual evidence of product efficacy.' },
  { id: 'Product Demonstration', label: 'Product Demonstration', desc: 'Feature-by-feature functionality breakdown and close-up performance.' },
  { id: 'Product Review', label: 'Product Review', desc: 'Honest creator evaluation, design breakdown, tactile features, final verdict.' },
  { id: 'Product Showcase', label: 'Product Showcase', desc: 'High-aesthetic commercial presentation focusing on craft, beauty, and texture.' },
  { id: 'Tutorial', label: 'Tutorial', desc: 'Step-by-step how-to guide demonstrating optimal usage and techniques.' },
  { id: 'Comparison', label: 'Comparison', desc: 'Side-by-side demonstration vs ordinary alternatives, highlighting superiority.' },
  { id: 'Transformation', label: 'Transformation', desc: 'Mood, physical, or environmental upgrade journey enabled by the product.' },
  { id: 'UGC Advertisement', label: 'UGC Advertisement', desc: 'Casual, relatable, smartphone-style creator ad optimized for TikTok/Reels.' },
  { id: 'Influencer Recommendation', label: 'Influencer Recommendation', desc: 'Credible influencer endorsement with personal favorite status.' },
  { id: 'Emotional Story', label: 'Emotional Story', desc: 'Narrative driven by human connection, empathy, nostalgia, or empowerment.' },
  { id: 'Educational Advertisement', label: 'Educational Advertisement', desc: 'Informing viewers about an underlying issue and how this innovation solves it.' },
  { id: 'Social Media Advertisement', label: 'Social Media Advertisement', desc: 'Fast-paced, hook-heavy viral format built for mobile feeds.' },
  { id: 'Custom Story', label: 'Custom Story', desc: 'Specify your own custom narrative arc and storyline.' },
] as const;

export const ADVERTISEMENT_STYLES = [
  { id: 'UGC NATURAL', label: 'UGC NATURAL', desc: 'Natural smartphone-style creator content with authentic casual aesthetics.' },
  { id: 'MIRROR CHECK', label: 'MIRROR CHECK', desc: 'Creator filming themselves through a mirror showing fit, style, and reaction.' },
  { id: 'POV HAND REVIEW', label: 'POV HAND REVIEW', desc: 'First-person perspective handheld product unboxing and tactile inspection.' },
  { id: 'SELFIE CAMERA', label: 'SELFIE CAMERA', desc: 'Direct front-facing smartphone selfie addressing the viewer intimately.' },
  { id: 'TALKING HEAD', label: 'TALKING HEAD', desc: 'Clean creator framing speaking directly to camera with authority and charm.' },
  { id: 'INFLUENCER REVIEW', label: 'INFLUENCER REVIEW', desc: 'Polished creator aesthetic with curated background and natural lighting.' },
  { id: 'LIFESTYLE CREATOR', label: 'LIFESTYLE CREATOR', desc: 'Cinematic daily-life vignettes showcasing seamless product utility.' },
  { id: 'PRODUCT SHOWCASE', label: 'PRODUCT SHOWCASE', desc: 'Product-focused commercial presentation emphasizing textures and angles.' },
  { id: 'CINEMATIC COMMERCIAL', label: 'CINEMATIC COMMERCIAL', desc: 'High-end cinema camera look, controlled lighting, and dramatic framing.' },
  { id: 'STUDIO PRODUCT', label: 'STUDIO PRODUCT', desc: 'Clean studio commercial lighting, precision pedestals, and pristine backdrop.' },
  { id: 'UNBOXING CREATOR', label: 'UNBOXING CREATOR', desc: 'Top-down or desk-level opening sequence highlighting packaging and feel.' },
  { id: 'BEFORE AFTER SOCIAL', label: 'BEFORE AFTER SOCIAL', desc: 'Side-by-side or split transformation format tailored for viral feeds.' },
  { id: 'FASHION EDITORIAL', label: 'FASHION EDITORIAL', desc: 'Vogue-style high-fashion editorial posing, striking composition, and mood.' },
  { id: 'BEAUTY COMMERCIAL', label: 'BEAUTY COMMERCIAL', desc: 'Luminous skin, macro drops, slow-motion application, and luxury glow.' },
  { id: 'CUSTOM', label: 'CUSTOM', desc: 'Define your own advertisement visual direction.' },
] as const;

export const CAMERA_ANGLES = [
  'Eye Level',
  'Close Up',
  'Extreme Close Up',
  'Medium Shot',
  'Medium Close Up',
  'Full Body',
  'Wide Shot',
  'Extreme Wide Shot',
  'Low Angle',
  'High Angle',
  'Over The Shoulder',
  'POV',
  'Top Down',
  'Dutch Angle',
  'Side Angle',
  'Three Quarter Angle',
  'Custom',
] as const;

export const CAMERA_MOVEMENTS = [
  'Static',
  'Handheld',
  'Slow Push In',
  'Pull Out',
  'Dolly In',
  'Dolly Out',
  'Pan Left',
  'Pan Right',
  'Tilt Up',
  'Tilt Down',
  'Tracking Shot',
  'Orbit',
  'Zoom In',
  'Zoom Out',
  'POV Movement',
  'Natural Smartphone Movement',
  'Custom',
] as const;

export const VISUAL_STYLES = [
  'Ultra Realistic',
  'Photorealistic',
  'Natural UGC',
  'Cinematic',
  'Luxury Commercial',
  'Minimalist',
  'Premium',
  'Fashion Editorial',
  'Beauty Commercial',
  'Social Media',
  'Documentary',
  'Street Style',
  'Studio',
  'Lifestyle',
  'Modern Advertisement',
  'Custom',
] as const;

export const LIGHTING_STYLES = [
  'Natural Daylight',
  'Soft Window Light',
  'Golden Hour',
  'Bright Commercial Lighting',
  'Soft Studio Lighting',
  'Dramatic Lighting',
  'Cinematic Lighting',
  'High Key',
  'Low Key',
  'Outdoor Natural Light',
  'Custom',
] as const;

export const ENVIRONMENTS = [
  'Home',
  'Bedroom',
  'Living Room',
  'Bathroom',
  'Kitchen',
  'Office',
  'Gym',
  'Street',
  'Cafe',
  'Outdoor',
  'Studio',
  'Shopping Mall',
  'Car',
  'Beach',
  'Nature',
  'Urban Environment',
  'Custom',
] as const;

export const DURATION_OPTIONS = [
  '5 sec',
  '10 sec',
  '15 sec',
  '20 sec',
  '30 sec',
  '45 sec',
  '60 sec',
] as const;

export const ASPECT_RATIOS = ['9:16', '16:9', '1:1', '4:5'] as const;

export const VIDEO_QUALITIES = ['Standard', 'High', 'Cinematic'] as const;

export const MOTION_INTENSITIES = ['Low', 'Medium', 'High'] as const;

export const VOICE_TYPES = ['Female', 'Male', 'Neutral'] as const;

export const VOICE_STYLES = [
  'Natural',
  'Friendly',
  'Energetic',
  'Calm',
  'Premium',
  'Emotional',
  'Persuasive',
  'Influencer',
] as const;

export const LANGUAGES = [
  'Indonesian',
  'English',
  'Arabic',
  'Malay',
  'Japanese',
  'Korean',
  'Spanish',
  'Custom',
] as const;

export const CTA_OPTIONS = [
  'No CTA',
  'Shop Now',
  'Buy Now',
  'Learn More',
  'Try It Now',
  'Order Today',
  'Check It Out',
  'Custom CTA',
] as const;

export const SAMPLE_PRESETS = [
  {
    id: 'sneaker',
    title: 'AeroPulse Carbon Runner',
    category: 'Footwear & Athletic',
    imagePath: '/src/assets/images/sample_product_sneaker_1790389207098.jpg',
    productName: 'AeroPulse Carbon Velocity Runner',
    productDescription: 'Ultralight marathon running shoe engineered with carbon composite propulsion plate, breathable hyper-mesh upper, and electric cyan ergonomic shock-absorbing sole.',
    sellingPoints: ['Carbon fiber plate', 'Sub-200g ultralight', 'Breathable aerodynamic mesh', 'Energy-return cushion', 'Reflective night accents'],
    targetAudience: 'Marathon runners, urban fitness enthusiasts, streetwear collectors aged 20-38',
    storyType: 'Problem → Solution',
    advertisementStyle: 'CINEMATIC COMMERCIAL',
    cameraAngles: ['Low Angle', 'Close Up', 'Medium Shot', 'POV'],
    cameraMovement: 'Tracking Shot',
    visualStyle: 'Cinematic',
    lighting: 'Dramatic Lighting',
    environment: 'Street',
    numberOfParts: 3,
    panelsPerPart: { 1: 3, 2: 4, 3: 3 },
    duration: '30 sec',
    aspectRatio: '9:16',
    voiceOver: true,
    voiceType: 'Male',
    voiceStyle: 'Energetic',
    language: 'English',
    dialogue: false,
    backgroundMusic: true,
    soundEffects: true,
    textOverlay: true,
    cta: 'Shop Now',
  },
  {
    id: 'serum',
    title: 'Lumen Botanics Radiance Serum',
    category: 'Skincare & Beauty',
    imagePath: '/src/assets/images/sample_product_skincare_1790389217856.jpg',
    productName: 'Lumen Botanics Super-Radiance Gold Serum',
    productDescription: 'Luxurious organic facial glow serum infused with botanical antioxidants, squalane, and vitamin C. Packaged in an amber apothecary glass bottle with gold dropper.',
    sellingPoints: ['Instant luminous glass skin', '100% cold-pressed botanicals', 'Deep cellular hydration', 'Non-greasy rapid absorption', 'Clean vegan formula'],
    targetAudience: 'Women and skincare enthusiasts 22-45 seeking glass-skin hydration',
    storyType: 'Before → After',
    advertisementStyle: 'BEAUTY COMMERCIAL',
    cameraAngles: ['Close Up', 'Extreme Close Up', 'Eye Level', 'Three Quarter Angle'],
    cameraMovement: 'Slow Push In',
    visualStyle: 'Beauty Commercial',
    lighting: 'Soft Window Light',
    environment: 'Bathroom',
    numberOfParts: 3,
    panelsPerPart: { 1: 2, 2: 3, 3: 2 },
    duration: '15 sec',
    aspectRatio: '9:16',
    voiceOver: true,
    voiceType: 'Female',
    voiceStyle: 'Calm',
    language: 'English',
    dialogue: false,
    backgroundMusic: true,
    soundEffects: true,
    textOverlay: true,
    cta: 'Try It Now',
  },
];

export const SAMPLE_MODEL = {
  id: 'mia',
  name: 'Mia Lin (Lifestyle Creator)',
  imagePath: '/src/assets/images/sample_model_creator_1790389229864.jpg',
  description: 'East Asian female creator, late 20s, shoulder-length natural black hair, radiant natural glow, wearing clean minimalist beige linen shirt.',
};
